---
# ServiceAccount for InfluxDB
apiVersion: v1
kind: ServiceAccount
metadata:
  name: influxdb
  namespace: debezium-example

---
# ClusterRoleBinding for InfluxDB (cluster-admin rights)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: influxdb-cluster-admin
subjects:
- kind: ServiceAccount
  name: influxdb
  namespace: debezium-example
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
# InfluxDB Deployment for Time-Series Data
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: debezium-example
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      serviceAccountName: influxdb
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: influxdb
        image: influxdb:2.7
        ports:
        - containerPort: 8086
          name: http
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: "setup"
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: "admin"
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: "admin123"
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: "trucks"
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: "locations"
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          value: "trucks-admin-token-12345"
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: influxdb-storage
          mountPath: /var/lib/influxdb2
        - name: influxdb-config
          mountPath: /etc/influxdb2
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 45
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8086
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      - name: influxdb-config
        emptyDir: {}

---
# InfluxDB Service
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: debezium-example
spec:
  selector:
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086
      name: http
  type: ClusterIP

---
# InfluxDB Route for external access
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: influxdb
  namespace: debezium-example
spec:
  to:
    kind: Service
    name: influxdb
  port:
    targetPort: http

