---
# Fresh Debezium MySQL Connector for demo.trucks.location topic
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: demo-trucks-connector
  namespace: debezium-example
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    # Database connection settings
    database.hostname: mysql
    database.port: "3306"
    database.user: debezium
    database.password: debezium
    database.server.id: "3001"
    database.server.name: demo-mysql-server
    
    # Database and table filtering - Focus on trucks database
    database.include.list: trucks
    table.include.list: trucks.location
    
    # Topic configuration - NEW PREFIX: demo
    topic.prefix: demo
    
    # Schema history configuration - NEW TOPIC
    schema.history.internal.kafka.bootstrap.servers: debezium-cluster-kafka-bootstrap:9092
    schema.history.internal.kafka.topic: demo-schema-history
    
    # Snapshot configuration - initial snapshot for fresh start
    snapshot.mode: initial
    snapshot.locking.mode: minimal
    
    # GTID configuration - allow both GTID and binlog position
    gtid.source.excludes: ""
    
    # Binlog configuration
    binlog.buffer.size: "8192"
    
    # Error handling and reliability
    errors.tolerance: none
    errors.log.enable: true
    errors.log.include.messages: true
    
    # Connection settings
    connect.keep.alive: "true"
    connect.keep.alive.interval.ms: "30000"
    connect.timeout.ms: "30000"
    
    # Performance settings
    max.batch.size: "1024"
    max.queue.size: "4096"
    poll.interval.ms: "1000"
    
    # Heartbeat configuration
    heartbeat.interval.ms: "10000"
    heartbeat.topics.prefix: __demo-heartbeat
    
    # Message key configuration - use id as the key
    message.key.columns: trucks.location:id
    
    # Include all location columns
    column.include.list: "trucks.location.id,trucks.location.latitude,trucks.location.longitude,trucks.location.created_at,trucks.location.updated_at"
    
    # Force decimal fields to be converted as strings to avoid base64 encoding
    decimal.handling.mode: "string"
