---
# Kafka Cluster Configuration for Debezium
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: debezium-cluster
  namespace: debezium-example
spec:
  kafka:
    version: 3.9.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      # Replication settings
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      
      # Protocol version
      inter.broker.protocol.version: "3.9"
    storage:
      type: ephemeral  # Use persistent storage in production
      
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral  # Use persistent storage in production
      
  entityOperator:
    topicOperator: {}
    userOperator: {}

