---
# MySQL Initialization Script ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: debezium-example
data:
  01-setup-debezium-user.sql: |
    -- Create debezium user with proper permissions for Change Data Capture
    CREATE USER IF NOT EXISTS 'debezium'@'%' IDENTIFIED BY 'debezium';
    
    -- Grant all necessary permissions for Debezium MySQL connector
    GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'debezium'@'%';
    GRANT ALL PRIVILEGES ON test.* TO 'debezium'@'%';
    
    -- Flush privileges to ensure they take effect
    FLUSH PRIVILEGES;
    
    -- Verify GTID and binlog settings
    SHOW VARIABLES LIKE 'gtid_mode';
    SHOW VARIABLES LIKE 'enforce_gtid_consistency';
    SHOW VARIABLES LIKE 'log_bin';
    SHOW VARIABLES LIKE 'binlog_format';

  02-create-sample-data.sql: |
    -- Switch to test database
    USE test;
    
    -- Create customers table
    CREATE TABLE IF NOT EXISTS customers (
        id INT AUTO_INCREMENT PRIMARY KEY,
        first_name VARCHAR(50) NOT NULL,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_email (email),
        INDEX idx_name (name)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
    
    -- Insert initial 10 customers
    INSERT INTO customers (first_name, name, email) VALUES
    ('John', 'Doe', 'john.doe@example.com'),
    ('Jane', 'Smith', 'jane.smith@example.com'),
    ('Michael', 'Johnson', 'michael.johnson@example.com'),
    ('Sarah', 'Williams', 'sarah.williams@example.com'),
    ('David', 'Brown', 'david.brown@example.com'),
    ('Emily', 'Davis', 'emily.davis@example.com'),
    ('Robert', 'Miller', 'robert.miller@example.com'),
    ('Lisa', 'Wilson', 'lisa.wilson@example.com'),
    ('James', 'Moore', 'james.moore@example.com'),
    ('Ashley', 'Taylor', 'ashley.taylor@example.com');
    
    -- Verify data was inserted
    SELECT COUNT(*) as initial_customer_count FROM customers;
    SELECT 'Sample data loaded successfully' as status;
