apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mqtt-listener-build
  namespace: mqtt
  labels:
    app: mqtt-listener
spec:
  output:
    to:
      kind: ImageStreamTag
      name: mqtt-listener:latest
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mqtt-listener
  namespace: mqtt
  labels:
    app: mqtt-listener

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-listener
  namespace: mqtt
  labels:
    app: mqtt-listener
    component: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-listener
  template:
    metadata:
      labels:
        app: mqtt-listener
        component: subscriber
    spec:
      containers:
      - name: mqtt-listener
        image: image-registry.openshift-image-registry.svc:5000/mqtt/mqtt-listener:latest
        env:
        - name: MQTT_BROKER
          value: "mosquitto.mqtt.svc"
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_TOPIC
          value: "trucks/all/locations"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        # Keep the container running and restart on failure
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
